# -*- coding: utf-8 -*-
"""Inteligencia de negocio - Alice Marrocos.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ovbNTCx0T9o5Ryo2Ywp5U1rJMxbY7wLi
"""

!pip install -q streamlit

import pandas as pd
import plotly.express as px
import streamlit as st

st.title('VACINAÇÃO -  Painel de Informações  Vacinação ')
st.set_page_config(page_title = 'DASHVACINA', layout = 'wide')

df = pd.read_csv('/content/vacinacao.csv')

df.info()

df['date'] = pd.to_datetime(df['date'])

fig1 = px.line(df, x = 'date', y = 'total_vaccinations',
               color = 'location',
               title = 'Total de pessoas vacinadas')
fig1.update_layout(xaxis_title = 'Data', yaxis_title = 'Total de pessoas vacinadas')
fig1.show()

st.plotly_chart(fig1, use_container_width=True)

df_filtro = df.query('location == "BRAZIL" or location == "INDIA" or location == "UNITED STATES"')
fig2 = px.pie(df_filtro,
               values = 'people_fully_vaccinated',

              names = 'location', title = 'Dados de pessoas totalmente vacinadas')
fig2.show()

# Verificando os valores únicos na coluna 'location' para depuração
print("Valores únicos na coluna 'location':")
display(df['location'].unique())

# Verificando a contagem de cada país
print("Contagem de ocorrências por 'location':")
display(df['location'].value_counts())

"""Com base nos valores únicos acima, podemos corrigir o filtro para `df_filtro`. Parece que os nomes dos países estão em letras minúsculas ou com alguma variação."""

# Correção do filtro para df_filtro, garantindo que os nomes dos países sejam correspondidos corretamente (ex: todos em maiúsculas para correspondência, ou verificar o caso exato)
# Supondo que os nomes dos países estão capitalizados (primeira letra maiúscula)
df_filtro_corrected = df.query('location == "Brazil" or location == "India" or location == "United States"').copy()

# Verificando se o DataFrame filtrado não está vazio agora
print("Informações do df_filtro_corrected:")
df_filtro_corrected.info()

display(df_filtro_corrected.head())

"""Agora que `df_filtro_corrected` deve conter dados, vamos criar um histograma para 'people_fully_vaccinated'."""

# Converter a coluna 'people_fully_vaccinated' para numérico, tratando 'none' como NaN
df_filtro_corrected['people_fully_vaccinated'] = pd.to_numeric(df_filtro_corrected['people_fully_vaccinated'], errors='coerce')

# Remover linhas com valores NaN nesta coluna para o histograma
df_histograma = df_filtro_corrected.dropna(subset=['people_fully_vaccinated'])

fig2_hist = px.histogram(df_histograma,
                         x='people_fully_vaccinated',
                         color='location',
                         title='Distribuição de Pessoas Totalmente Vacinadas')

fig2_hist.update_layout(bargap=0.1) # Espaçamento entre as barras do histograma
fig2_hist.show()

# Converter a coluna 'people_fully_vaccinated' para numérico, tratando 'none' como NaN
df_filtro_corrected['people_fully_vaccinated'] = pd.to_numeric(df_filtro_corrected['people_fully_vaccinated'], errors='coerce')

# Agrupar por localização e somar as pessoas totalmente vacinadas
df_pie = df_filtro_corrected.groupby('location')['people_fully_vaccinated'].max().reset_index()

# Remover linhas com valores NaN para o gráfico de pizza
df_pie = df_pie.dropna(subset=['people_fully_vaccinated'])

fig3 = px.pie(df_pie,
               values = 'people_fully_vaccinated',
               names = 'location',
               title = 'Dados comparativos de pessoas totalmente vacinadas')
fig3.show()

st.plotly_chart(fig2, use_container_width=True)